identity:
  association:
    # cron schedule to move expired associations
    expire: '0 0 0 * * ?'
  session:
    # cron schedule to delete expired sessions
    expire: '0 0 0 * * ?'
  # 10 years
  associationTTL: 311040000

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost/identity'
    username: 'jeon'
    password: 'jeon'
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
